// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/cinema/cinemapro.proto

/*
Package go_micro_srv_cinamaservice is a generated protocol buffer package.

It is generated from these files:
	proto/cinema/cinemapro.proto

It has these top-level messages:
	RequestAllMovies
	RequestMovie
	ResponseAllMovies
	ResponseMovie
	ResponseMovieStream
	MovieSimpleProto
	MovieProto
	ActorProto
	DirectorProto
	MovieTypeProto
	MovieLanguagesProto
	MovieGenresProto
*/
package go_micro_srv_cinamaservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for CinamaWorldService service

type CinamaWorldService interface {
	GetAllMoviesSingleStream(ctx context.Context, in *RequestAllMovies, opts ...client.CallOption) (CinamaWorldService_GetAllMoviesSingleStreamService, error)
	GetMovieByMovieId(ctx context.Context, in *RequestMovie, opts ...client.CallOption) (*ResponseMovie, error)
	GetAllMoviesStream(ctx context.Context, in *RequestAllMovies, opts ...client.CallOption) (CinamaWorldService_GetAllMoviesStreamService, error)
}

type cinamaWorldService struct {
	c    client.Client
	name string
}

func NewCinamaWorldService(name string, c client.Client) CinamaWorldService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.cinamaservice"
	}
	return &cinamaWorldService{
		c:    c,
		name: name,
	}
}

func (c *cinamaWorldService) GetAllMoviesSingleStream(ctx context.Context, in *RequestAllMovies, opts ...client.CallOption) (CinamaWorldService_GetAllMoviesSingleStreamService, error) {
	req := c.c.NewRequest(c.name, "CinamaWorldService.GetAllMoviesSingleStream", &RequestAllMovies{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &cinamaWorldServiceGetAllMoviesSingleStream{stream}, nil
}

type CinamaWorldService_GetAllMoviesSingleStreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ResponseAllMovies, error)
}

type cinamaWorldServiceGetAllMoviesSingleStream struct {
	stream client.Stream
}

func (x *cinamaWorldServiceGetAllMoviesSingleStream) Close() error {
	return x.stream.Close()
}

func (x *cinamaWorldServiceGetAllMoviesSingleStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *cinamaWorldServiceGetAllMoviesSingleStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *cinamaWorldServiceGetAllMoviesSingleStream) Recv() (*ResponseAllMovies, error) {
	m := new(ResponseAllMovies)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cinamaWorldService) GetMovieByMovieId(ctx context.Context, in *RequestMovie, opts ...client.CallOption) (*ResponseMovie, error) {
	req := c.c.NewRequest(c.name, "CinamaWorldService.GetMovieByMovieId", in)
	out := new(ResponseMovie)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cinamaWorldService) GetAllMoviesStream(ctx context.Context, in *RequestAllMovies, opts ...client.CallOption) (CinamaWorldService_GetAllMoviesStreamService, error) {
	req := c.c.NewRequest(c.name, "CinamaWorldService.GetAllMoviesStream", &RequestAllMovies{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &cinamaWorldServiceGetAllMoviesStream{stream}, nil
}

type CinamaWorldService_GetAllMoviesStreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ResponseMovieStream, error)
}

type cinamaWorldServiceGetAllMoviesStream struct {
	stream client.Stream
}

func (x *cinamaWorldServiceGetAllMoviesStream) Close() error {
	return x.stream.Close()
}

func (x *cinamaWorldServiceGetAllMoviesStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *cinamaWorldServiceGetAllMoviesStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *cinamaWorldServiceGetAllMoviesStream) Recv() (*ResponseMovieStream, error) {
	m := new(ResponseMovieStream)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for CinamaWorldService service

type CinamaWorldServiceHandler interface {
	GetAllMoviesSingleStream(context.Context, *RequestAllMovies, CinamaWorldService_GetAllMoviesSingleStreamStream) error
	GetMovieByMovieId(context.Context, *RequestMovie, *ResponseMovie) error
	GetAllMoviesStream(context.Context, *RequestAllMovies, CinamaWorldService_GetAllMoviesStreamStream) error
}

func RegisterCinamaWorldServiceHandler(s server.Server, hdlr CinamaWorldServiceHandler, opts ...server.HandlerOption) {
	type cinamaWorldService interface {
		GetAllMoviesSingleStream(ctx context.Context, stream server.Stream) error
		GetMovieByMovieId(ctx context.Context, in *RequestMovie, out *ResponseMovie) error
		GetAllMoviesStream(ctx context.Context, stream server.Stream) error
	}
	type CinamaWorldService struct {
		cinamaWorldService
	}
	h := &cinamaWorldServiceHandler{hdlr}
	s.Handle(s.NewHandler(&CinamaWorldService{h}, opts...))
}

type cinamaWorldServiceHandler struct {
	CinamaWorldServiceHandler
}

func (h *cinamaWorldServiceHandler) GetAllMoviesSingleStream(ctx context.Context, stream server.Stream) error {
	m := new(RequestAllMovies)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.CinamaWorldServiceHandler.GetAllMoviesSingleStream(ctx, m, &cinamaWorldServiceGetAllMoviesSingleStreamStream{stream})
}

type CinamaWorldService_GetAllMoviesSingleStreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ResponseAllMovies) error
}

type cinamaWorldServiceGetAllMoviesSingleStreamStream struct {
	stream server.Stream
}

func (x *cinamaWorldServiceGetAllMoviesSingleStreamStream) Close() error {
	return x.stream.Close()
}

func (x *cinamaWorldServiceGetAllMoviesSingleStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *cinamaWorldServiceGetAllMoviesSingleStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *cinamaWorldServiceGetAllMoviesSingleStreamStream) Send(m *ResponseAllMovies) error {
	return x.stream.Send(m)
}

func (h *cinamaWorldServiceHandler) GetMovieByMovieId(ctx context.Context, in *RequestMovie, out *ResponseMovie) error {
	return h.CinamaWorldServiceHandler.GetMovieByMovieId(ctx, in, out)
}

func (h *cinamaWorldServiceHandler) GetAllMoviesStream(ctx context.Context, stream server.Stream) error {
	m := new(RequestAllMovies)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.CinamaWorldServiceHandler.GetAllMoviesStream(ctx, m, &cinamaWorldServiceGetAllMoviesStreamStream{stream})
}

type CinamaWorldService_GetAllMoviesStreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ResponseMovieStream) error
}

type cinamaWorldServiceGetAllMoviesStreamStream struct {
	stream server.Stream
}

func (x *cinamaWorldServiceGetAllMoviesStreamStream) Close() error {
	return x.stream.Close()
}

func (x *cinamaWorldServiceGetAllMoviesStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *cinamaWorldServiceGetAllMoviesStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *cinamaWorldServiceGetAllMoviesStreamStream) Send(m *ResponseMovieStream) error {
	return x.stream.Send(m)
}
